name: Build and Deploy Web Game

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame-ce pygbag
        
    - name: Build web version
      run: |
        cd web
        python -m pygbag main.py \
          --width 1280 \
          --height 720 \
          --name "Asteroids Game - 1000 Levels" \
          --archive \
          --ume_block 0 \
          --cdn "https://cdn.jsdelivr.net/pyodide/" \
          --template custom
          
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/dist
        cname: asteroids-game.pages.dev
